_BASE_: ../oneformer_R50_bs16_50ep.yaml
MODEL:
  BACKBONE:
    NAME: "D2DiNAT"
  DiNAT:
    EMBED_DIM: 192
    MLP_RATIO: 2.0
    DEPTHS: [3, 4, 18, 5]
    NUM_HEADS: [6, 12, 24, 48]
    KERNEL_SIZE: 11
    DROP_PATH_RATE: 0.3
    DILATIONS: [[1, 20, 1], [1, 5, 1, 10], [1, 2, 1, 3, 1, 4, 1, 5, 1, 2, 1, 3, 1, 4, 1, 5, 1, 5], [1, 2, 1, 2, 1]]
  WEIGHTS: "dinat_large_in22k_in1k_384_11x11.pkl"
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.120, 57.375]
  ONE_FORMER:
    NUM_OBJECT_QUERIES: 150
SOLVER:
  STEPS: (655556, 710184)
  MAX_ITER: 737500
  AMP:
    ENABLED: False
TEST:
  DETECTIONS_PER_IMAGE: 150